### ISSUE TITLE
Panic unlock of unlocked mutex

### ISSUE THREAD

**Issue by s-kostyaev** [saibing/bingo#121]
Panic on latest master
[bingo-panic.log](https://github.com/saibing/bingo/files/2904048/bingo-panic.log)

**Comment by fjl** [comment]
I looked at this too and the problem seems to be that locking in project.go is very inconsistent:

There is `Project.viewMu` that protects the `Project.view` field but it's not used consistently. There are three places where Project code locks the current `View`. This panic can happen if `Project.view` is updated while the lock on the current `View` is held. In that case the unlock call will happen on a different instance of `View` than the one that was locked.

**Comment by saibing** [comment]
@s-kostyaev @fjl 

Yes, the root cause of this problem is on Project.viewMu. I will slove it as soon as possible
